development:
  host: localhost
  database: pophealth-development

test:
  host: <%= ENV['TEST_DB_HOST'] || 'localhost' %>
  database: pophealth-test

# set these environment variables on your prod server
production:
  host: localhost
  database: pophealth-production